//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuckBot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpermitted keywords have been found in the code..
        /// </summary>
        internal static string err_badcode {
            get {
                return ResourceManager.GetString("err_badcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error.
        /// </summary>
        internal static string err_compile {
            get {
                return ResourceManager.GetString("err_compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        internal static string err_generic {
            get {
                return ResourceManager.GetString("err_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} with specified name exists..
        /// </summary>
        internal static string err_nogeneric {
            get {
                return ResourceManager.GetString("err_nogeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with specified code isn&apos;t available..
        /// </summary>
        internal static string err_nolanguage {
            get {
                return ResourceManager.GetString("err_nolanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subcommand specified..
        /// </summary>
        internal static string err_nosubcmd {
            get {
                return ResourceManager.GetString("err_nosubcmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only human server administrators can use this command!.
        /// </summary>
        internal static string err_notadmin {
            get {
                return ResourceManager.GetString("err_notadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient amount of parameters specified..
        /// </summary>
        internal static string err_params {
            get {
                return ResourceManager.GetString("err_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have sufficent permissons..
        /// </summary>
        internal static string err_permissions {
            get {
                return ResourceManager.GetString("err_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script execution timed out!.
        /// </summary>
        internal static string err_scrtimeout {
            get {
                return ResourceManager.GetString("err_scrtimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting gracefully.
        /// </summary>
        internal static string exit_end {
            get {
                return ResourceManager.GetString("exit_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down DuckBot....
        /// </summary>
        internal static string exit_start {
            get {
                return ResourceManager.GetString("exit_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        internal static string lab_action {
            get {
                return ResourceManager.GetString("lab_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command.
        /// </summary>
        internal static string lab_cmd {
            get {
                return ResourceManager.GetString("lab_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        internal static string lab_content {
            get {
                return ResourceManager.GetString("lab_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languageCode.
        /// </summary>
        internal static string lab_language {
            get {
                return ResourceManager.GetString("lab_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal string.
        /// </summary>
        internal static string lab_literal {
            get {
                return ResourceManager.GetString("lab_literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string lab_message {
            get {
                return ResourceManager.GetString("lab_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string lab_name {
            get {
                return ResourceManager.GetString("lab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string lab_optional {
            get {
                return ResourceManager.GetString("lab_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string lab_required {
            get {
                return ResourceManager.GetString("lab_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string lab_type {
            get {
                return ResourceManager.GetString("lab_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string lab_user {
            get {
                return ResourceManager.GetString("lab_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user-made command.
        /// </summary>
        internal static string lab_usercmd {
            get {
                return ResourceManager.GetString("lab_usercmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string lab_var {
            get {
                return ResourceManager.GetString("lab_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed from: {0}
        ///To: {1}.
        /// </summary>
        internal static string ret_changes {
            get {
                return ResourceManager.GetString("ret_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: `{0} {1}`
        ///Notation: `{2}`.
        /// </summary>
        internal static string ret_cmdhelp {
            get {
                return ResourceManager.GetString("ret_cmdhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name: `{0}`
        ///Created: `{1}` by `{2}`.
        /// </summary>
        internal static string ret_cmdinfo {
            get {
                return ResourceManager.GetString("ret_cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, I&apos;ll deliver the message when {0} goes online.
        /// </summary>
        internal static string ret_delivery {
            get {
                return ResourceManager.GetString("ret_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to didn&apos;t return anything..
        /// </summary>
        internal static string ret_empty {
            get {
                return ResourceManager.GetString("ret_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command didn&apos;t return anything..
        /// </summary>
        internal static string ret_empty_cmd {
            get {
                return ResourceManager.GetString("ret_empty_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script didn&apos;t return anything..
        /// </summary>
        internal static string ret_empty_script {
            get {
                return ResourceManager.GetString("ret_empty_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} `{1}`..
        /// </summary>
        internal static string ret_removed {
            get {
                return ResourceManager.GetString("ret_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        internal static string ret_success {
            get {
                return ResourceManager.GetString("ret_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token file has wrong format!.
        /// </summary>
        internal static string start_err_badtoken {
            get {
                return ResourceManager.GetString("start_err_badtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load file &apos;{0}&apos;!.
        /// </summary>
        internal static string start_err_fileload {
            get {
                return ResourceManager.GetString("start_err_fileload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token file hasn&apos;t been found!.
        /// </summary>
        internal static string start_err_notoken {
            get {
                return ResourceManager.GetString("start_err_notoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}, press &apos;Q&apos; to quit!.
        /// </summary>
        internal static string start_info {
            get {
                return ResourceManager.GetString("start_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was removed from the inbox:.
        /// </summary>
        internal static string title_fullinbox {
            get {
                return ResourceManager.GetString("title_fullinbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in commands list:.
        /// </summary>
        internal static string title_hardcmdlist {
            get {
                return ResourceManager.GetString("title_hardcmdlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages from `{0}`:.
        /// </summary>
        internal static string title_inbox {
            get {
                return ResourceManager.GetString("title_inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-made commands list:.
        /// </summary>
        internal static string title_usercmdlist {
            get {
                return ResourceManager.GetString("title_usercmdlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable list:.
        /// </summary>
        internal static string title_varlist {
            get {
                return ResourceManager.GetString("title_varlist", resourceCulture);
            }
        }
    }
}
